apiVersion: v1
kind: Service
metadata:
  name: spring-boot-ddb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-ddb

