apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-ddb-wo-crac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-ddb-wo-crac
  template:
    metadata:
      labels:
        app: spring-boot-ddb-wo-crac
    spec:
      serviceAccountName: spring-boot-ddb
      containers:
      - name: spring-boot-ddb-wo-crac
        image: 656220021423.dkr.ecr.eu-west-1.amazonaws.com/spring-demo:v11-checkpoint
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          capabilities:
            add:
              - all
          privileged: true
          runAsUser: 0
          allowPrivilegeEscalation: true
        command: ["/bin/bash"]
        args: ["/opt/scripts/run-service-wo-crac.sh"]
